project_name: github_billing_exporter
release:
  github:
    owner: raynigon
    name: github_billing_exporter
builds:
  - id: github_billing_exporter
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: github_billing_exporter.go
    ldflags: -s -w
      -X github.com/raynigon/github_billing_exporter/version.version={{.Version}}
      -X github.com/raynigon/github_billing_exporter/version.gitSHA={{.Commit}}
      -X github.com/raynigon/github_billing_exporter/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: github_billing_exporter
    hooks: {}
dockers:
  - dockerfile: "./Dockerfile"
    ids:
      - github_billing_exporter
    image_templates:
    - "raynigon/github_billing_exporter:latest"
    - "raynigon/github_billing_exporter:{{ .Tag }}"
    - "raynigon/github_billing_exporter:v{{ .Major }}"
archives:
  - id: github_billing_exporter
    builds:
      - github_billing_exporter
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
