name: build-and-test

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: make
